using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ASVSSECURITYAUDITOR.Core.Interfaces;
using ASVSSECURITYAUDITOR.Core.Entities;
using ASVSSECURITYAUDITOR.Infrastructure.Data;

namespace ASVSSECURITYAUDITOR.Core.Services
{
    public class PdfReportService : IPdfReportService
    {
        private readonly ApplicationDbContext _context;

        public PdfReportService(
            ApplicationDbContext context)
        {
            _context = context;
        }

        public byte[] GenerateAssessmentReport(
            int assessmentId)
        {
            var assessment = _context
                .Assessments
                .Include(x => x.Items)
                .ThenInclude(x => x.ASVSRequirement)
                .FirstOrDefault(x => x.Id == assessmentId);

            var total = assessment.Items.Count;

            var valid = assessment.Items
                .Count(x => x.Status == AssessmentStatus.Valid);

            double compliance =
                total == 0
                ? 0
                : ((double)valid / total) * 100;

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("OWASP ASVS Security Report")
                        .FontSize(24)
                        .Bold();

                    page.Content()
                        .PaddingVertical(20)
                        .Column(col =>
                        {
                            col.Spacing(10);

                            col.Item().Text(
                                $"Assessment: {assessment.Name}");

                            col.Item().Text(
                                $"Date: {assessment.CreatedAt}");

                            col.Item().Text(
                                $"Compliance: {compliance:F2}%");

                            col.Item().PaddingTop(20);

                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("Code").Bold();
                                    header.Cell().Text("Requirement").Bold();
                                    header.Cell().Text("Status").Bold();
                                });

                                foreach (var item in assessment.Items)
                                {
                                    table.Cell().Text(
                                        item.ASVSRequirement.RequirementCode);

                                    table.Cell().Text(
                                        item.ASVSRequirement.Title);

                                    table.Cell().Text(
                                        item.Status.ToString());
                                }
                            });
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by ");
                            x.Span("ASVS Security Auditor")
                                .Bold();
                        });
                });
            });

            return document.GeneratePdf();
        }
    }
}